### PR TITLE
start service before using it

### PR DESCRIPTION
**Pull request by duck-rh**

### CODE REVIEW

**Comment by mscherer** [comment]
So the role is not yet portable to merge. I do not think that's a priority to modernize it but that's something to be done I guess.

**Comment by duck-rh** [comment]
I needed it to work to integrate it elsewhere. I saw no other drawbacks at the moment.
Having several mysql/mariadb roles arround gives me spots and headaches so…

**Comment by duck-rh** [comment]
affects Fedora 25

**Comment by duck-rh** [comment]
Ok, no one complained on this and I'm really bored by this problem, so I'm taking responsibility in merging it.

**Pull request merged**
